server:
  port: 9292
  servlet:
    context-path: /api
  compression:
    enabled: true
  http2:
    enabled: true
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 300MB
      max-request-size: 300MB
  application:
    name: mom-edu-admin
  profiles:
    active: development
  jpa:
    database: default
    generate-ddl: false
    database-platform: org.hibernate.dialect.MariaDB103Dialect
  flyway:
    baseline-on-migrate: true



